# Project: Project6
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.o
LINKOBJ  = ../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lfreeglut -lopengl32 -lglu32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ProyectoEF3D.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.o: ../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.cpp
	$(CPP) -c ../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.cpp -o ../../../EF/modelo-escena-grupo3-BRANCHDEBELEN01/ProyectoEF/main.o $(CXXFLAGS)
